### ISSUE TITLE
fine tuning with pre-trained model

### ISSUE THREAD

**Issue by zeydabadi** [neurosity/EEG-GPT#6]
Hi, 
I downloaded the pre-trained model from your 'read me' section and tried to run this fine-tuning command:
`python train_gpt.py --training-style='decoding' --num-decoding-classes=4 --training-steps=10000       --eval_every_n_steps=1000 --log-every-n-steps=1000 --num_chunks=2 --per-device-training-batch-size=32 --per-device-validation-batch-size=32  --chunk_len=500 --chunk_ovlp=0 --run-name='BCI_fine_tune_NoPreTrain' --fold_i=0 --num-encoder-layers=6 --num-hidden-layers=6 --learning-rate=1e-4 --use-encoder='True' --embedding-dim=1024 --dst-data-path='/BCIC/bciiv2a_eeg_npz/' --dst-data-channel-count=22 --pretrained-model='/pretrained/model.safetensors'`

However, I'm getting this error:
`Traceback (most recent call last):
  File "/data/work/zeydabadi/EEG-GPT/src/train_gpt.py", line 1077, in <module>
    trainer = train()
  File "/data/work/zeydabadi/EEG-GPT/src/train_gpt.py", line 242, in train
    trainer = make_trainer(
  File "/data/work/zeydabadi/EEG-GPT/src/trainer/make.py", line 248, in make_trainer
    trainer = Trainer(
  File "/data/work/zeydabadi/EEG-GPT/src/trainer/base.py", line 58, in __init__
    super().__init__(**kwargs)
  File "/data/home1/zeydabadi/braindecode/lib/python3.10/site-packages/transformers/trainer.py", line 419, in __init__
    model = self.call_model_init()
  File "/data/home1/zeydabadi/braindecode/lib/python3.10/site-packages/transformers/trainer.py", line 1573, in call_model_init
    model = self.model_init(trial)
  File "/data/work/zeydabadi/EEG-GPT/src/train_gpt.py", line 235, in model_init
    return make_model(model_config)
  File "/data/work/zeydabadi/EEG-GPT/src/train_gpt.py", line 396, in make_model
    model.load_state_dict(state_dict)
  File "/data/home1/zeydabadi/braindecode/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
	Missing key(s) in state_dict: "decoder.decoding_head.0.weight", "decoder.decoding_head.0.bias", "decoder.decoding_head.3.weight", "decoder.decoding_head.3.bias", "decoder.decoding_head.6.weight", "decoder.decoding_head.6.bias". 
	size mismatch for encoder.patch_embedding.shallownet.1.weight: copying a param with shape torch.Size([40, 40, 21, 1]) from checkpoint, the shape in current model is torch.Size([40, 40, 22, 1]).
`
I appreciate your input to fix this error.

Thanks,

**Comment by oreHGA** [comment]
Hey @zeydabadi , just pushed an update to trim the number of channels from downstream task to match the pretrained model... They're both expecting 21 channels - this can change based on your own datasets

Added more details about the model run here also https://github.com/neurosity/EEG-GPT/pull/7
